from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from datetime import datetime
import os
import uuid

def generate_pdf_report(result, symptoms, patient_name, patient_age, image_path, language):
    """
    Generate a professional PDF medical report
    """
    # Create reports directory if it doesn't exist
    os.makedirs("reports", exist_ok=True)
    
    # Generate unique filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_id = str(uuid.uuid4())[:8]
    filename = f"reports/MedSeek_Report_{timestamp}_{report_id}.pdf"
    
    # Create PDF document
    doc = SimpleDocTemplate(filename, pagesize=A4,
                           rightMargin=72, leftMargin=72,
                           topMargin=72, bottomMargin=18)
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=12,
        alignment=TA_JUSTIFY
    )
    
    # Add title
    elements.append(Paragraph("🏥 MedSeek Medical Report", title_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Add report metadata
    report_data = [
        ['Report ID:', report_id],
        ['Generated:', datetime.now().strftime("%B %d, %Y at %I:%M %p")],
        ['Language:', language]
    ]
    
    if patient_name:
        report_data.insert(0, ['Patient Name:', patient_name])
    if patient_age:
        report_data.insert(1, ['Age:', patient_age])
    
    metadata_table = Table(report_data, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e0e7ff')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    elements.append(metadata_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Add disclaimer
    disclaimer = Paragraph(
        "<b>DISCLAIMER:</b> This report is generated by an AI system for informational purposes only. "
        "It does not constitute medical advice, diagnosis, or treatment. Always consult qualified healthcare "
        "professionals for proper medical care.",
        ParagraphStyle('Disclaimer', parent=normal_style, textColor=colors.red, fontSize=9)
    )
    elements.append(disclaimer)
    elements.append(Spacer(1, 0.2*inch))
    
    # Add symptoms section
    elements.append(Paragraph("📋 Reported Symptoms", heading_style))
    if symptoms:
        elements.append(Paragraph(symptoms, normal_style))
    else:
        elements.append(Paragraph("Image-based analysis only", normal_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Add image if available
    if image_path and os.path.exists(image_path):
        elements.append(Paragraph("📸 Medical Image", heading_style))
        try:
            img = Image(image_path, width=4*inch, height=3*inch)
            elements.append(img)
            elements.append(Spacer(1, 0.2*inch))
        except:
            elements.append(Paragraph("Image could not be loaded", normal_style))
    
    # Add diagnostic findings
    elements.append(Paragraph("🔬 Diagnostic Analysis", heading_style))
    
    findings_data = [
        ['Identified Condition:', result.get('disease', 'N/A')],
        ['Confidence Level:', result.get('confidence', 'N/A')],
        ['Recommended Specialist:', result.get('specialist', 'N/A')]
    ]
    
    findings_table = Table(findings_data, colWidths=[2.5*inch, 3.5*inch])
    findings_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#dbeafe')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'TOP')
    ]))
    elements.append(findings_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # Add medications
    elements.append(Paragraph("💊 Recommended Medications", heading_style))
    medications = result.get('medications', [])
    for i, med in enumerate(medications, 1):
        elements.append(Paragraph(f"{i}. {med}", normal_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Add preventions
    elements.append(Paragraph("🛡️ Preventions & Care Instructions", heading_style))
    preventions = result.get('preventions', [])
    for i, prev in enumerate(preventions, 1):
        elements.append(Paragraph(f"{i}. {prev}", normal_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Add additional notes
    if result.get('notes'):
        elements.append(Paragraph("📝 Additional Notes", heading_style))
        elements.append(Paragraph(result.get('notes', ''), normal_style))
        elements.append(Spacer(1, 0.2*inch))
    
    # Add footer
    elements.append(Spacer(1, 0.3*inch))
    footer_text = Paragraph(
        "This report was generated by MedSeek AI Medical Assistant. "
        "For questions or concerns, please consult with a qualified healthcare provider.",
        ParagraphStyle('Footer', parent=normal_style, fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
    )
    elements.append(footer_text)
    
    # Build PDF
    doc.build(elements)
    
    return filename
